### ISSUE TITLE
Investigate providing mirrors for files

### ISSUE THREAD

**Issue by rianniello** [ausaccessfed/shibboleth-idp-installer#10]
We may require mirroring of artifacts used by the installer.

There have been reliability issues with some urls. If these problems persist and cause issues for users of the installer we may need to move to an AAF managed provider.

**Comment by bradleybeddoes** [comment]
Closing this for now, we may reconsider this post release if users report wider problems with failed resources but for now they mostly seem to be reliable. 

Relying on remote repositories seems to be a smarter approach given our limited team size as well.
