### ISSUE TITLE
Add files for editting to enable redirect CAS login page

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp-installer#108]
The following files: 
conf/authn/general-authn.xml - add authn/Shibcas bean
conf/idp.properties -  Additional CAS options
    - shibcas.casServerUrlPrefix
    - shibcas.casServerLoginUrl
    - shibcas.serverName
JAR files
    - cas-client-core-3.3.3.jar
    - shib-cas-authenticator-3.0.0.jar

**Comment by jbirdman** [comment]
The authn flow files are also missing under flows/authn/Shibcas:

- shibcas-authn-beans.xml
- shibcas-authn-flow.xml
