### ISSUE TITLE
SharedToken DataConnector fails if using sAMAccountName

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp-installer#145]
If the SharedToken DataConnector defeins the SOURCE_ATTRIBUTE_ID=sAMAccountName but does not define an AttributeDefinition for the sAMAccountName then it will fail complaining that it could not resolve a value for the sAMAccountName.

I think this should be fixed in the auEduPersonSharedToken generator library, but for now a workaround of defening an AttributeDefinition for the sAMAccountName works. Adding the following fo the attribute-reslover.xml.

    <resolver:AttributeDefinition xsi:type="ad:Simple" id="sAMAccountName" sourceAttributeID="sAMAccountName">
        <resolver:Dependency ref="ldap" />
    </resolver:AttributeDefinition>

**Comment by abrahad** [comment]
Added to the common error page
