### ISSUE TITLE
Decide on SHA signing algorithm

### ISSUE THREAD

**Issue by rianniello** [ausaccessfed/shibboleth-idp-installer#19]
Currently in the default idp.properties

```
# To default to SHA-1, set to shibboleth.SigningConfiguration.SHA1
#idp.signing.config = shibboleth.SigningConfiguration.SHA256
```

From Shibboleth 2 which may not be relevant anymore:
https://wiki.shibboleth.net/confluence/display/SHIB2/Changing+IdP+Signature+Method+Algorithm

**Comment by bradleybeddoes** [comment]
We *should* actually be able to get away with leaving this as default at least my testing thus far has shown that.

Going to leave this issue open incase any future input, wrt SP testing, changes this position but for now we'll leave as is.
