### ISSUE TITLE
Current installations: set `utf8mb4` as default encoding for `tb_st`.`uid`

### ISSUE THREAD

**Issue by rcaught** [ausaccessfed/shibboleth-idp-installer#247]
Currently, the encoding used by the `uid` column in the `tb_st` table is not explicitly set.
https://github.com/ausaccessfed/shibboleth-idp-installer/blob/develop/templates/db/tb_st_ddl.sql

This means that `uid` characters outside of the `latin1` character set are stored as `?` and not respected by the Shared Token database lookups.

This results in:
- These type of `uid`'s being computed each time (not a big deal).
- Any custom Shared Tokens migrated from another University, that have a `uid` associated (with characters outside of the `latin1` range) will not be returning the stored (custom) value, only an incorrect generated value.

Existing setups should set this column to have a character set of `utf8mb4` (available in MySQL 5.5+) and a collation of `utf8mb4_bin`.

**Comment by rcaught** [comment]
I am amending this to using a collation of `utf8mb4_unicode_ci`.

**Comment by trsau** [comment]
Resolved by bugfix/tb_st_encoding
