### ISSUE TITLE
Too many messages

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp-installer#33]
There is too much output generated by both bootstrap and update from Ansible.

These should be logged to a time stamped files, and optionally shown if some DEBUG flag is enabled.

On completion of the script the user should be informed that a log of actions is available and can be found at ...

**Comment by bradleybeddoes** [comment]
Note in docs that output is deliberately verbose and can be ignored if no error state is generated.

In addition log all Ansible runs, possibly by using:
http://docs.ansible.com/ansible/intro_configuration.html#log-path

Location of log file should also be noted in docs before bootstrap is run.

**Comment by trsau** [comment]
I'm not in favor of verbose logging to standard out as the default.

Logging of event to file must apply to both bootstrap and update.
