### ISSUE TITLE
README or WARNING files

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp-installer#37]
Add README or WARNING files to all directories that should NOT be modified by the IdP owner. These files should direct the IdP owner to location where they can safely modify the files.

**Comment by bradleybeddoes** [comment]
As discussed in aaf-tech we won't be pursuing this.

The overhead will outweigh derived benefit. We need to trust administrators to read the documentation provided and properly put into place processes for working with the delivered system as they would any other system they are operating for their organisation.
