### ISSUE TITLE
WARNING headers in files

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp-installer#38]
Add WARNING headers to files that should not be modified by the IdP owner. These WARNING should direct the user IdP owner to the location of the file where they can safely modify its content.

**Comment by bradleybeddoes** [comment]
As discussed in aaf-tech we won't be pursuing this.

The overhead will outweigh derived benefit. We need to trust administrators to read the documentation provided and properly put into place processes for working with the delivered system as they would any other system they are operating for their organisation.
