### ISSUE TITLE
Importing SALT values from and earlier IdP

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp-installer#39]
There does not seem to be anywhere the IdP owner can enter the SALT values used be an earlier version of their IDP. This will assist in upgrading from V2 IdPs

**Comment by bradleybeddoes** [comment]
@trsau: Associated with your documentation on undertaking an upgrade. Will leave for you to close.

**Comment by trsau** [comment]
Documented in the upgrade doco
