### ISSUE TITLE
Is it safe to re-run the bootstrap.sh script a second or subsequent time?

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp-installer#42]
Is it safe to re-run the bootstrap.sh script a second or subsequent time?

Should this be detected and the IdP owner informed to run the update.sh script instead.

When I re-ran bootstrap.sh it broke my IdP because I had only update values in the assets directory, not in the bootstrap.sh file. I assume bootstrap.sh over rights stuff.

**Comment by bradleybeddoes** [comment]
@trsau can you please add some additional context here about exactly what you did so it can be re-produced. 

A previously unidentified bug withstanding, re-running bootstrap.sh should be safe.

**Comment by trsau** [comment]
You make your edits to the bootstrap.sh file making a mistake in say the LDAP_BASE_DN for instance.

After you run the bootstrap and do some testing you realize where you have made the mistake so you correct the error in the file /opt/shibboleth-idp-installer/repository/assets/idp.example.edu.au/idp/conf/ldap.properties and run the update script which fixes the problem.

Now the configuration in bootstrap is out of sync with the configuration in assets. Re-running bootstrap will re-introduce the error that was corrected in ldap.properties.

**Comment by bradleybeddoes** [comment]
We're going to mark bootstrap.sh as destructive.

A message will be output if a temporary file exists preventing duplicate executions (and advising how to force execution if absolutely required).

**Comment by bradleybeddoes** [comment]
Closed by #75 and #46
