### ISSUE TITLE
No information is provided about registering the ECP endpoint in FR.

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp-installer#44]
The ECP endpoint is not automatically registered as part of the IDP registration in FR. It currently needs to be registered after the initial registration. 

This should be added to the Installation finalization steps

**Comment by bradleybeddoes** [comment]
This will addressed by a new FR build to limit duplication:

https://github.com/ausaccessfed/federationregistry/issues/206

**Comment by bradleybeddoes** [comment]
This has been addressed in FR, and will be default for all created IdP in FR 2.5 and later

https://github.com/ausaccessfed/federationregistry/pull/207
