### ISSUE TITLE
Option to define a re-direct URL for the server

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp-installer#45]
Either provide an option for the IdP Owner to define a URL which can be redirected to if the end user tries to go to the root of the server, ie the user see https://idp.example.edu.au/idp/profile/SAML2 and they try going to https://idp.example.edu.au the installer currently provides the message: Forbidden You don't have permission to access / on this server. 

Or provide documentation that informs the IdP Owner that they should consider changing so it redirects to a appropriate location.

**Comment by bradleybeddoes** [comment]
Duplicates #7.

Leaving both open for now.

**Comment by bradleybeddoes** [comment]
Going to close for brevity, tracking in #7.
