### ISSUE TITLE
Make the IdP Status page accessible to the AAF Monitoring service, or at least its content.

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp-installer#49]
The IdP Status page provides information about the IdP  and JDK software versions. Being able to monitor this a flag when version fall too far behind would assist in ensuring that IdP software is being maintained and patched.

The restrictions are currently based on IP address in the access-control.xml file. There is currently only one Access control policy defined. This is them used to protect status, resolvertest and reload admin functions. As only Status is the only one being that may be exposed to monitor a new policy should be created. 

Also being IP address controlled there is an issue with sustainability, in particular if the IP address of monitor changes, which is likely in the near future.

 Access to this information is important in the long term for support, how it is technically accessed may be provided by some other more sustainable approach...

**Comment by bradleybeddoes** [comment]
The shibboleth docs regarding this currently state:

    This facility supports the creation of named policies that implement particular access control rules, so
    that the policies can be shared and attached by name to particular services. At present, the only policy  
    implementation supplied relies on IP range controls. This will likely be extended in the future as we 
    work to integrate the IdP's own authentication layer so that enterprise authentication can be leveraged 
    for access to the IdP itself.

Given limiting by IP isn't scalable we'll revisit this issue in the future when a better solution exists.

**Comment by trsau** [comment]
Closing this issue as it should be resolved by the Business Intelligence service that is under development.
