### ISSUE TITLE
REDHAT compatibility

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp-installer#50]
REDHAT does not have an epel-release package so bootstrap.sh fails when is attempts to install it. 

Additional documentation ror REDHAT, the 'optional' repository (rhel-7-server-optional-rpms) and 'extras' repository (rhel-7-server-extras-rpms) need to be available to the server.

Modify bootstrap.sh so it only attempts to install epel-release if on a Centos 7 server.

**Comment by bradleybeddoes** [comment]
@trsau Do you have the exact commands available that you ran to configure these?

**Comment by trsau** [comment]
On the REDHAT box for QUT i did the following...

wget http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
rpm -ivh epel-release-7-5.noarch.rpm

I have also talked to QUT's system admin folk that for sites that use the REDHAT package management system, all they should need to do is enable the appropriate repos. rhel-7-server-optional-rpms and rhel-7-server-extras-rpms. This is prefered so the server does not try to go outside the boundaries of the organisation to get the repos.

I will get the QUT box re-imaged with these options enabled and verify.
