### ISSUE TITLE
Change how the Shibboleth install.sh is called

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp-installer#53]
Currently the Shibboleth IdP install.sh script is call using expect which looks for particular strings and sends an appropriate response as the script runs. All of the items that are passed to the Shib install script can be passed vai documented values in ANT_OPTS allow us to run install.sh directly. The following example shows all values that are currently sent via expect being passed via ANT_OPTS...

This seems simpler than wrapping another layer around the Shibboleth install.sh script

#!/bin/sh
set -e
export ANT_OPTS=" \
      -Didp.src.dir=/opt/shibboleth/shibboleth-src/shibboleth-identity-provider-3.1.2 \
      -Didp.target.dir=/opt/shibboleth/shibboleth-idp/shibboleth-idp-3.1.2 \
      -Didp.host.name=idp.example.edu.au \
      -Didp.entityID=https://idp.example.edu.au/idp/shibboleth \
      -Didp.scope=example.edu.au \
      -Didp.keystore.password=yXkxCvj2zSOeY0Lr0puFvrfhtJPx1BYf2tTWEzc... \
      -Didp.sealer.password=gfA9tzwZi5LnR8d8tuPgZ7JFUyGuRaKFR7yGPn2YJ... \
      -Didp.noprompt=true"
export JAVA_HOME="/usr/lib/jvm/java"
sh /opt/shibboleth/shibboleth-src/shibboleth-identity-provider-3.1.2/bin/install.sh

**Comment by trsau** [comment]
Minor change to the file as trying to set the entityID does not work, it is created from idp.host.name. Also using the appropriate template variables. This works on Bond University's IdPs.

```
#!/bin/sh
set -e
export ANT_OPTS=" \
      -Didp.src.dir={{ shib_idp.src }} \
      -Didp.target.dir={{ shib_idp.home }} \
      -Didp.host.name={{ idp_host_name }} \
      -Didp.scope={{ idp_attribute_scope }} \
      -Didp.keystore.password={{ shib_idp.keystore_password }} \
      -Didp.sealer.password={{ shib_idp.cookie_enc_key_password }} "
export JAVA_HOME="/usr/lib/jvm/java"
sh {{ shib_idp.src }}/bin/install.sh
```

**Comment by bradleybeddoes** [comment]
@trsau this is some awesome help, really appreciate it.

![cheers!](http://www.quickmeme.com/img/e6/e6ecab80668a6c6221e727f3ec246996416ab3a12a1043c25f3500a3e27fe8a9.jpg)

Will do some additional tests on my host and get it into Alpha 2 code later today.

@smangelsdorf this gets around that weird expect issue we saw yesterday. I still have no idea how/why that host was broken.

![aliens](https://s-media-cache-ak0.pinimg.com/736x/7e/5e/4d/7e5e4d5d39e03763edeb3ab51a6291b1.jpg)
