### ISSUE TITLE
Make jetty.sh ansible managed 

### ISSUE THREAD

**Issue by rianniello** [ausaccessfed/shibboleth-idp-installer#8]
We're encountering problems where the packaged `jetty.sh` start up / shut down script. 

The biggest problem is the `started()` script times out after 60 seconds

``` sh
started()
{
  # wait for 60s to see "STARTED" in PID file, needs jetty-started.xml as argument
  for T in 1 2 3 4 5 6 7 9 10 11 12 13 14 15
  do
    sleep 4
    [ -z "$(grep STARTED $1 2>/dev/null)" ] || return 0
    [ -z "$(grep STOPPED $1 2>/dev/null)" ] || return 1
    [ -z "$(grep FAILED $1 2>/dev/null)" ] || return 1
    local PID=$(cat "$2" 2>/dev/null) || return 1
    kill -0 "$PID" 2>/dev/null || return 1
    echo -n ". "
  done

  return 1;
}
```

Shibboleth IdP takes a long time to boot, much longer than a minute typically. We must modify this part to allow for a larger timeout.

Along with this, the script there appears to have a lot of moving parts that could be removed. Unused environment variables etc. We need to cull ones we aren’t using / improve things where we can.

It will save time in the future by making this script maintainable / easier to debug.

**Comment by trsau** [comment]
Resolved by bugfix/jetty-startup
